# Generated by Django 2.1.2 on 2019-03-27 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('relation', models.CharField(choices=[('1', 'Father'), ('2', 'Mother'), ('3', 'Brother'), ('4', 'Sister'), ('5', 'wife'), ('6', 'husband')], max_length=1)),
                ('dob', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,13}$')])),
            ],
        ),
    ]
